// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://adkvnvpkmiibanzsjcif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFka3ZudnBrbWlpYmFuenNqY2lmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NTc5OTMsImV4cCI6MjA2NDUzMzk5M30.iv6YX8o6WEI5X6-LmoHvzJTF-tbBy3CqMEpofUz0hl8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);