// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fuzbkwbaazwoghtadgvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1emJrd2JhYXp3b2dodGFkZ3ZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwOTY5NzYsImV4cCI6MjA3NTY3Mjk3Nn0.V_ayzMk0TKilFsWbYH9ed72-LOMGky_3RWfP6lojuQs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});